// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBZ8HMgeNUpOK2J030v9ntAHZwqMfbfSI',
    appId: '1:539727816233:web:53b3ba09ff64ff43345e38',
    messagingSenderId: '539727816233',
    projectId: 'rentacycle-app',
    authDomain: 'rentacycle-app.firebaseapp.com',
    storageBucket: 'rentacycle-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKNYAFe6POTbm4wmyj81vTJwQYHc2dSaU',
    appId: '1:539727816233:android:11a52e869c6a539e345e38',
    messagingSenderId: '539727816233',
    projectId: 'rentacycle-app',
    storageBucket: 'rentacycle-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPKlMCYz6kfSqzIowMwp6V5r__aN3Ctyc',
    appId: '1:539727816233:ios:7e4ce2f7863a11e7345e38',
    messagingSenderId: '539727816233',
    projectId: 'rentacycle-app',
    storageBucket: 'rentacycle-app.firebasestorage.app',
    iosBundleId: 'com.example.rentacycle',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPKlMCYz6kfSqzIowMwp6V5r__aN3Ctyc',
    appId: '1:539727816233:ios:7e4ce2f7863a11e7345e38',
    messagingSenderId: '539727816233',
    projectId: 'rentacycle-app',
    storageBucket: 'rentacycle-app.firebasestorage.app',
    iosBundleId: 'com.example.rentacycle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBZ8HMgeNUpOK2J030v9ntAHZwqMfbfSI',
    appId: '1:539727816233:web:95a6a93b0b89971e345e38',
    messagingSenderId: '539727816233',
    projectId: 'rentacycle-app',
    authDomain: 'rentacycle-app.firebaseapp.com',
    storageBucket: 'rentacycle-app.firebasestorage.app',
  );
}
